# Generated by Django 5.2.5 on 2025-10-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
