# Generated by Django 5.2.6 on 2025-10-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_name',
            new_name='category_names',
        ),
    ]
