# Generated by Django 5.2.5 on 2025-10-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category_name',
        ),
    ]
