# Generated by Django 5.2.5 on 2025-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
