# Generated by Django 5.2.5 on 2025-10-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
