# Generated by Django 5.2.7 on 2025-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_chapter_duration_course_badge_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_materials/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
