# Generated by Django 5.2.7 on 2025-10-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_chapter_description_alter_chapter_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
