# Generated by Django 5.2.5 on 2025-10-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_category_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True / False'), ('short', 'Short Answer'), ('pdf', 'PDF Document')], max_length=20),
        ),
    ]
